name: ğŸš€ Deploy & Quality Assurance

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  constents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflown }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name:  deploy to Github pages
    runs-on: ubuntu-latest
    iF: github.ref == 'refs/heads'
    outputs:
      page_url: ${{ steps.deployment.outputs.page.page_url }}

    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page.page_url }}

    steps:
      - name: ğŸ“¤ Checkout code
        uses: actions/Checkout@v4

      - name: ğŸ“„ Setup Pages
        uses: actions/configure-pages@v4

      - name: ğŸ“¦ Upload artifact
        uses: actions/Upload-pages-artifact@v3
        with:
          path: "."

      - name: ğŸš€ Deploy to Github pages
        id: deployment
        uses: actions/deploy-pages@